name: AccuKnox Container Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build local Docker image
        run: |
          docker build -t test-nginx:latest .

      - name: Run AccuKnox Container Scanner
        uses: Vickydew1/container-scan-action@Docker
        with:
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          
          image_name: "test-nginx"
          tag: "latest"
          
          dockerfile_context: "Dockerfile"
          
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
          soft_fail: true
          upload_results: true
          generate_sbom: true
          project_name: "Project Test"
